apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flex-reisetilskudd-cronjob-starter
  namespace: flex
  labels:
    team: flex

spec:
  schedule: "0-59/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gpr-credentials
          containers:
            - name: flex-reisetilskudd-cronjob-starter
              image: {{ image }}
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "200m"
                limits:
                  memory: "1024Mi"
                  cpu: "500m"
  accessPolicy:
    outbound:
      external:
        - host: www.vg.no
      rules:
        - application: flex-reisetilskudd-backend
